### ISSUE TITLE
Awesome 🎯 

### ISSUE THREAD

**Issue by ByteSizedIT** [fac22/microblogging_site-DASE#23]
First things first, Awesome! 🤩 

Great project and still only week 1!

✅ post my thoughts so others can read them
✅ read what other people have posted
✅ delete my posts so no one can see them anymore
✅ No .html files (all HTML responses should be created dynamically within Node)
✅ No client-side JavaScript (all logic should happen on the server)
✅ All static assets served correctly (CSS, favicon etc)
✅ Cypress Tests 
✅ A responsive, mobile-first design

Oh, and deployed on Heroku as a little extra 😉

**Comment by ByteSizedIT** [comment]
First things first, Awesome! 🤩 

Great project and still only week 1!

✅ post my thoughts so others can read them
✅ read what other people have posted
✅ delete my posts so no one can see them anymore
✅ No .html files (all HTML responses should be created dynamically within Node)
✅ No client-side JavaScript (all logic should happen on the server)
✅ All static assets served correctly (CSS, favicon etc)
✅ Cypress Tests 
✅ A responsive, mobile-first design

👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

**Comment by elenamarinaki** [comment]
Thank you on behalf of the team @ByteSizedIT :)
