### ISSUE TITLE
📚 Read Me 📚

### ISSUE THREAD

**Issue by ByteSizedIT** [fac22/microblogging_site-DASE#28]
😍 Good job including a read me - also like the way you have styled it in line with the project and your USP. Certainly makes it stand out.

Maybe it would be good to add some additional sections at the bottom - e.g how to install your project locally/run tests.

You might find this link useful - https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/ 😍

**Comment by jamdelion** [comment]
I agree, I appreciate the wittiness but would love to have seen a screenshot of the site so I know what to expect :)
